package com.dataSonification.v2.sound;

public class JavaGM {
//	 Suppress default constructor for noninstantiability
	private JavaGM() {}
	
	public static String[] patch = {
			"Piano",
			"Bright Piano",
			"Electric Grand",
			"Honky Tonk Piano",
			"Electric Piano 1",
			"Electric Piano 2",
			"Harpsichord",
			"Clavinet",
			"Celesta",
			"Glockenspiel", 
			"Music Box",        // 10
			"Vibraphone",
			"Marimba",
			"Xylophone",
			"Tubular Bell",
			"Dulcimer",
			"Hammond Organ",
			"Perc Organ",
			"Rock Organ",
			"Church Organ", 
			"Reed Organ",       // 20
			"Accordion",
			"Harmonica",
			"Tango Accordion",
			"Nylon Str Guitar",
			"Steel String Guitar",
			"Jazz Electric Gtr",
			"Clean Guitar",
			"Muted Guitar",
			"Overdrive Guitar", 
			"Distortion Guitar",    // 30
			"Guitar Harmonics",
			"Acoustic Bass",
			"Fingered Bass",
			"Picked Bass",
			"Fretless Bass",
			"Slap Bass 1",
			"Slap Bass 2",
			"Syn Bass 1",
			"Syn Bass 2", 
			"Violin",               // 40
			"Viola",
			"Cello",
			"Contrabass",
			"Tremolo Strings",
			"Pizzicato Strings",
			"Orchestral Harp",
			"Timpani",
			"Ensemble Strings",
			"Slow Strings",  
			"Synth Strings 1",      // 50
			"Synth Strings 2",
			"Choir Aahs",
			"Voice Oohs",
			"Syn Choir",
			"Orchestra Hit",
			"Trumpet",
			"Trombone",
			"Tuba",
			"Muted Trumpet",  
			"French Horn",          // 60
			"Brass Ensemble",
			"Syn Brass 1",
			"Syn Brass 2",
			"Soprano Sax",
			"Alto Sax",
			"Tenor Sax",
			"Baritone Sax",
			"Oboe",
			"English Horn", 
			"Bassoon",              // 70
			"Clarinet",
			"Piccolo",
			"Flute",
			"Recorder",
			"Pan Flute",
			"Bottle Blow",
			"Shakuhachi",
			"Whistle",
			"Ocarina",
			"Syn Square Wave",      // 80
			"Syn Saw Wave",         
			"Syn Calliope",
			"Syn Chiff",
			"Syn Charang",
			"Syn Voice",
			"Syn Fifths Saw",
			"Syn Brass and Lead",
			"Fantasia",
			"Warm Pad",
			"Polysynth",            //90
			"Space Vox",            
			"Bowed Glass",
			"Metal Pad",
			"Halo Pad",
			"Sweep Pad",
			"Ice Rain",
			"Soundtrack",
			"Crystal",
			"Atmosphere",
			"Brightness",           // 100
			"Goblins",              
			"Echo Drops",
			"Sci Fi",
			"Sitar",
			"Banjo",
			"Shamisen",
			"Koto",
			"Kalimba",
			"Bag Pipe",
			"Fiddle",              // 110
			"Shanai", 
			"Tinkle Bell",
			"Agogo",
			"Steel Drums",
			"Woodblock",
			"Taiko Drum",
			"Melodic Tom",
			"Syn Drum",
			"Reverse Cymbal",
			"Guitar Fret Noise",  // 120
			"Breath Noise",
			"Seashore",
			"Bird",
			"Telephone",
			"Helicopter",
			"Applause",
			"Gunshot",
			"Hi-Q",
			"Slap",
			"Scratch Push",       // 130
			"Scratch Pull",
			"Sticks",
			"Square Click",
			"Metronome Click",
			"Metronome Bell",
			"Low Kick",
			"Kick",
			"Rimclik",
			"Acoustic Snare",
			"Handclap",           // 140
			"Electric Snare",
			"Tom Low",
			"Closed Hi-Hat",
			"Tom Hi",
			"Pedal Hi-Hat",
			"Tom Hi",
			"Open Hi-Hat",
			"Low Mid Tom",
			"High Mid Tom",
			"Crash Cymbal 1",
			"High Tom",             // 150
			"Ride Cymbal 1",
			"Chinese Cymbal",
			"Ride Bell",
			"Tambourine",
			"Splash Cymbal",
			"Cowbell",
			"Crash Cymbal 2",
			"Vibraslap",
			"Ride Cymbal 2",           // 160
			"High Bongo",
			"Low Bongo",
			"Mute High Conga",
			"Open High Conga",
			"Low Conga",
			"High Timbale",
			"Low Timbale",
			"High Agogo",
			"Low Agogo",
			"Cabasa",             // 170
			"Maracas", 
			"Short Whistle",
			"Long Whistle",
			"Short Guiro",
			"Long Guiro",
			"Claves",
			"High Wood Block",
			"Low Wood Block",
			"Mute Cuica",
			"Open Cuica",       // 180
			"Close Triangle",
			"Open Triangle",
			"Shaker",
			"Jingle Bell",
			"Bell Tree",
			"Castanets",
			"Mute Surdo",
			"Open Surdo",
			"Brush Snare High",
			"Brush Snare Low",        // 190
			"Soft Piano",   
			"Reflection Piano",
			"Flange Piano",
			"Octopus Piano",
			"Flange Electric Piano",
			"Tremolo Electric Piano",
			"Chorus Harpsichord",
			"Ondioline",
			"Curious Chime",
			"Swirly Bell",           // 200
			"Echo Bell", 
			"Vibraphone 2",
			"Soft Marimba",
			"Percolator",
			"Reverse Bell",
			"Percussive Piano",
			"Rot. Speaker Organ 1",
			"Bright Perc Organ",
			"Growl Organ",
			"Chorus Church Organ",           // 210
			"Sawteeth",  
			"Expressive Accordion",
			"Corny Harmonica",
			"Squeeze Box",
			"Acoustic Bass Gtr",
			"Mute Guitar 2",
			"Chorus Jazz Guitar",
			"Tremolo Guitar",
			"Echo Mute Bass",
			"Grungey Guitar",       // 220
			"Flange Guitar", 
			"Flange Guitar Stab",
			"Dark Syn Bass",
			"Jungle Bass",
			"Jungle Bass 2",
			"Chorus Bass",
			"Synth Slap Bass",
			"Lowrider",
			"OB Bass",
			"OB Bass 2",        // 230
			"Synth Violin", 
			"Robot Threat",
			"Formula 1",
			"Deep Bass Stab",
			"Trill Strings",
			"Cello Stroke",
			"VibHarp",
			"Tuned Drum",
			"sfz Strings",
			"Moving Strings",       // 240
			"Heads of Space",
			"Slow Synth Strings",
			"Slow Choir Aahs",
			"Pulsing Voices",
			"Cloudscapes",
			"Hype Orch Hit",
			"Accent Trumpet",
			"Accent Trombone",
			"Mellow Trombone",
			"Muted Trumpet 2",    // 250
			"French Horn Swell",
			"Brass Ensemble 2",
			"Syn Brass 3",
			"Syn Brass 4",
			"Lyrical Sax",
			"Accent Sax",
			"Slow Sax",
			"Staccato Sax",
			"Lyrical Oboe",
			"Soft Lead Synth",     // 260
			"Staccato Bassoon",
			"Smooth Clarinet",
			"Accent Piccolo",
			"Lyrical Flute",
			"Mello Breath",
			"Peruvian",
			"Breath Echoes",
			"Apparition",
			"Humorous Whistle",
			"Strobes",           // 270
			"Teletronic",
			"5th Pulse",
			"Moon Jelly",
			"Ricochet Pad",
			"Rock Radiation",
			"Solo Vox 2",
			"5th Saw Drone",
			"Lead Synth 2",
			"Fantasy Bells",
			"Slow Warm Pad",          // 280
			"Polysynth 2",
			"50's Sci-Fi",
			"Watery Glass",
			"UFOs",
			"Soprano",
			"Refractions",
			"Comet Tails",
			"Soundtrack 2",
			"Friendly Data",
			"Analog Sequence",       // 290
			"Luminous Voice",
			"Goblins 2",
			"Tick Blok",
			"Droplet",
			"Droplet 2",
			"Video Game 1",
			"Video Game 2",
			"Digi-Dodo",
			"Fairy Godmother",
			"Alarm",             //300
			"Hoverbug",
			"Crickets",
			"Beatnik",
			"Teletype",
			"Carriage Return",
			"Typewriter Key",
			"Cash Register",
			"Thru Phone Chirp",
			"Whipped",
			"Pop Click",          // 310
			"Metal Chirp",
			"Poing",
			"Metal Spray",
			"FlyBy 1",
			"FlyBy 2",
			"Cosmic Ray",
			"SampHold",
			"SampHold 2",
			"tablaesque_lo",
			"tablaesque_hi",        // 320
			"nine_inch_kick",
			"hippishake",
			"ScienceTom",
			"click",
			"rvs cymb pan long",
			"rvs cymb pan med",
			"rvs cymb pan shrt",
			"woodstick",
			"electrobrite", 
			"SloLaser",            // 330
			"ufo-by",
			"air snare",
			"weird snare",
			"flange snare",
			"ping drum",
			"itchy-scratch",
			"itchy-scratch2",
			"hi_metallic_snare",
			"noise echo",
			"buzzy hit",            // 340
			"rez_hat",
			"bucket hit",
			"icecube",
			"explosive kick",
			"mutant cowbell",
			"Temple Bell",
			"Hi Temple Gong",
			"Thuddy Kick",
			"LoBell",
			"sinechirp",            // 350
			"hollow_metal_hit",
			"woodblock",
			"reverse cymbal",
			"tablaesque_slap",
			"sonarblip",
			"sinehit",
			"sineblock",
			"Krelltone",
			"sine_kick",
			"hi-tone*",             // 360
			"hi-click",
			"Gate-tone",
			"chem-tone",
			"dub_kick",
			"Untitled",
		};
}